### ISSUE TITLE
Abandoned package nette/reflection

### ISSUE THREAD

**Issue by petrparolek** [contributte/nextras-orm-events#22]
Package nette/reflection is abandoned, you should avoid using it. No replacement was suggested.

**Comment by f3l1x** [comment]
nette/reflection is stable and working. But yes, we should try something else.

Can you please prepare a PR with change?

**Comment by f3l1x** [comment]
Resolved https://github.com/contributte/nextras-orm-events/commit/ee62a717a248175f013ea9ff16624a8224d00edd
